// IT role catalog: each role's expected market tech stack and a fixed, rule-based
// market-demand rating out of 15. Each IC role is paired with a "Lead" variant that
// bumps the stack up one-to-two levels of seniority and adds leadership responsibilities.
// Update this list as the job market shifts.
export const IT_ROLES = [
  {
    id: 'java-backend',
    label: 'Java Backend Developer',
    marketDemand: { label: 'High demand', points: 13 },
    coreStack: [
      { id: 'core-java', label: 'Core Java (8/11/17+)' },
      { id: 'spring-boot', label: 'Spring Boot' },
      { id: 'hibernate-jpa', label: 'Hibernate / JPA' },
      { id: 'rest-apis', label: 'REST API design' },
      { id: 'microservices', label: 'Microservices architecture' },
      { id: 'sql-db', label: 'SQL (PostgreSQL/MySQL)' },
      { id: 'kafka', label: 'Kafka / messaging queues' },
      { id: 'docker', label: 'Docker' },
      { id: 'kubernetes', label: 'Kubernetes' },
      { id: 'cicd-cloud', label: 'CI/CD + a cloud platform (AWS/Azure/GCP)' },
    ],
  },
  {
    id: 'java-backend-lead',
    label: 'Java Backend Lead',
    marketDemand: { label: 'High demand', points: 12 },
    coreStack: [
      { id: 'advanced-java', label: 'Advanced Java (concurrency, JVM tuning)' },
      { id: 'spring-boot-scale', label: 'Spring Boot at scale (distributed systems)' },
      { id: 'microservices-patterns', label: 'Microservices architecture & design patterns' },
      { id: 'event-driven', label: 'Event-driven architecture (Kafka)' },
      { id: 'db-scaling', label: 'Database performance & scaling' },
      { id: 'cloud-native-arch', label: 'Cloud-native architecture (AWS/Azure/GCP)' },
      { id: 'system-design', label: 'System design & architecture ownership' },
      { id: 'code-review-mentoring', label: 'Code review & mentoring' },
      { id: 'tech-roadmap', label: 'Technical roadmap & delivery ownership' },
      { id: 'stakeholder-comms', label: 'Cross-team stakeholder communication' },
    ],
  },
  {
    id: 'fullstack',
    label: 'Full Stack Developer',
    marketDemand: { label: 'High demand', points: 13 },
    coreStack: [
      { id: 'frontend-fundamentals', label: 'Frontend fundamentals (HTML/CSS/JavaScript, React)' },
      { id: 'backend-framework', label: 'Backend framework (Node.js/Express, Django, or Spring)' },
      { id: 'rest-apis', label: 'REST API design' },
      { id: 'sql-nosql', label: 'Databases (SQL & NoSQL)' },
      { id: 'auth', label: 'Authentication & authorization' },
      { id: 'docker', label: 'Docker' },
      { id: 'cloud-platform', label: 'A cloud platform (AWS/Azure/GCP)' },
      { id: 'git-cicd', label: 'Git & CI/CD' },
      { id: 'testing-fullstack', label: 'Testing (unit & integration)' },
      { id: 'typescript', label: 'TypeScript' },
    ],
  },
  {
    id: 'fullstack-lead',
    label: 'Full Stack Lead',
    marketDemand: { label: 'High demand', points: 12 },
    coreStack: [
      { id: 'fullstack-architecture', label: 'End-to-end architecture (frontend + backend systems)' },
      { id: 'api-design-microservices', label: 'Advanced API design (REST/GraphQL) & microservices' },
      { id: 'db-design-scaling', label: 'Database design & scaling' },
      { id: 'cloud-native-arch', label: 'Cloud-native architecture (AWS/Azure/GCP)' },
      { id: 'cicd-ownership', label: 'CI/CD pipeline ownership' },
      { id: 'security-best-practices', label: 'Security best practices (authN/authZ, OWASP)' },
      { id: 'system-design', label: 'System design & architecture ownership' },
      { id: 'code-review-mentoring', label: 'Code review & mentoring' },
      { id: 'tech-roadmap', label: 'Technical roadmap & delivery ownership' },
      { id: 'stakeholder-comms', label: 'Cross-team stakeholder communication' },
    ],
  },
  {
    id: 'frontend',
    label: 'Frontend Developer',
    marketDemand: { label: 'High demand', points: 12 },
    coreStack: [
      { id: 'html-css', label: 'HTML5 / CSS3' },
      { id: 'javascript-es6', label: 'Modern JavaScript (ES6+)' },
      { id: 'react', label: 'React' },
      { id: 'typescript', label: 'TypeScript' },
      { id: 'state-mgmt', label: 'State management (Redux/Zustand/Context)' },
      { id: 'api-integration', label: 'REST/GraphQL API integration' },
      { id: 'testing-fe', label: 'Testing (Jest/React Testing Library)' },
      { id: 'build-tools', label: 'Build tooling (Vite/Webpack)' },
      { id: 'accessibility', label: 'Responsive design & accessibility' },
      { id: 'git-cicd', label: 'Git & CI/CD' },
    ],
  },
  {
    id: 'frontend-lead',
    label: 'Frontend Lead',
    marketDemand: { label: 'High demand', points: 11 },
    coreStack: [
      { id: 'advanced-react', label: 'Advanced React (performance, architecture patterns)' },
      { id: 'typescript-arch', label: 'Type-safe architecture at scale' },
      { id: 'frontend-arch', label: 'Frontend architecture & micro-frontends' },
      { id: 'design-systems', label: 'Design systems & component libraries' },
      { id: 'performance-opt', label: 'Performance optimization & Core Web Vitals' },
      { id: 'testing-strategy', label: 'Testing strategy ownership (unit/e2e)' },
      { id: 'code-review-mentoring', label: 'Code review & mentoring' },
      { id: 'design-product-collab', label: 'Cross-team collaboration with design/product' },
      { id: 'tech-roadmap', label: 'Technical roadmap ownership' },
      { id: 'engineering-standards', label: 'Accessibility & engineering standards ownership' },
    ],
  },
  {
    id: 'python-backend',
    label: 'Python Backend Developer',
    marketDemand: { label: 'Very high demand', points: 14 },
    coreStack: [
      { id: 'python-core', label: 'Core Python' },
      { id: 'django-fastapi', label: 'Django or FastAPI' },
      { id: 'rest-apis', label: 'REST API design' },
      { id: 'sql-orm', label: 'SQL & ORM (SQLAlchemy/Django ORM)' },
      { id: 'async-programming', label: 'Async programming (asyncio)' },
      { id: 'docker', label: 'Docker' },
      { id: 'kubernetes', label: 'Kubernetes' },
      { id: 'cloud-platform', label: 'A cloud platform (AWS/Azure/GCP)' },
      { id: 'testing-py', label: 'Testing (pytest)' },
      { id: 'cicd', label: 'CI/CD pipelines' },
    ],
  },
  {
    id: 'python-backend-lead',
    label: 'Python Backend Lead',
    marketDemand: { label: 'Very high demand', points: 13 },
    coreStack: [
      { id: 'advanced-python', label: 'Advanced Python (async at scale, performance tuning)' },
      { id: 'framework-arch-scale', label: 'Django/FastAPI architecture at scale' },
      { id: 'distributed-systems', label: 'Distributed systems & microservices design' },
      { id: 'db-scaling', label: 'Database scaling & optimization' },
      { id: 'cloud-native-arch', label: 'Cloud-native architecture (AWS/Azure/GCP)' },
      { id: 'event-driven', label: 'Event-driven / streaming architecture' },
      { id: 'system-design', label: 'System design & architecture ownership' },
      { id: 'code-review-mentoring', label: 'Code review & mentoring' },
      { id: 'tech-roadmap', label: 'Technical roadmap & delivery ownership' },
      { id: 'stakeholder-comms', label: 'Cross-team stakeholder communication' },
    ],
  },
  {
    id: 'devops-cloud',
    label: 'DevOps / Cloud Engineer',
    marketDemand: { label: 'Very high demand', points: 15 },
    coreStack: [
      { id: 'linux', label: 'Linux administration' },
      { id: 'cloud-platform', label: 'A cloud platform (AWS/Azure/GCP)' },
      { id: 'terraform', label: 'Infrastructure as Code (Terraform)' },
      { id: 'docker', label: 'Docker' },
      { id: 'kubernetes', label: 'Kubernetes' },
      { id: 'cicd-pipelines', label: 'CI/CD pipelines (Jenkins/GitHub Actions)' },
      { id: 'scripting', label: 'Scripting (Bash/Python)' },
      { id: 'monitoring', label: 'Monitoring (Prometheus/Grafana)' },
      { id: 'networking-security', label: 'Networking & security fundamentals' },
      { id: 'git', label: 'Git' },
    ],
  },
  {
    id: 'devops-cloud-lead',
    label: 'DevOps / Cloud Lead',
    marketDemand: { label: 'Very high demand', points: 14 },
    coreStack: [
      { id: 'multi-cloud-strategy', label: 'Multi-cloud architecture strategy' },
      { id: 'advanced-k8s', label: 'Advanced Kubernetes (multi-cluster, service mesh)' },
      { id: 'iac-at-scale', label: 'Infrastructure as Code at scale (Terraform modules)' },
      { id: 'sre-practices', label: 'Site reliability engineering (SRE) practices' },
      { id: 'security-compliance', label: 'Security & compliance architecture' },
      { id: 'finops', label: 'Cost optimization (FinOps)' },
      { id: 'incident-management', label: 'Incident management / on-call ownership' },
      { id: 'code-review-mentoring', label: 'Mentoring & infrastructure review' },
      { id: 'platform-strategy', label: 'Cross-team platform strategy' },
      { id: 'stakeholder-comms', label: 'Stakeholder communication' },
    ],
  },
  {
    id: 'data-engineer',
    label: 'Data Engineer',
    marketDemand: { label: 'Very high demand', points: 14 },
    coreStack: [
      { id: 'python-sql', label: 'Python & SQL' },
      { id: 'etl-elt', label: 'ETL/ELT pipeline design' },
      { id: 'data-warehouse', label: 'Data warehousing (Snowflake/BigQuery/Redshift)' },
      { id: 'spark', label: 'Apache Spark' },
      { id: 'airflow', label: 'Workflow orchestration (Airflow)' },
      { id: 'cloud-data', label: 'Cloud data services (AWS/Azure/GCP)' },
      { id: 'streaming', label: 'Streaming (Kafka)' },
      { id: 'data-modeling', label: 'Data modeling' },
      { id: 'docker', label: 'Docker' },
      { id: 'cicd', label: 'CI/CD pipelines' },
    ],
  },
  {
    id: 'data-engineer-lead',
    label: 'Data Engineering Lead',
    marketDemand: { label: 'Very high demand', points: 13 },
    coreStack: [
      { id: 'lakehouse-arch', label: 'Advanced data architecture (lakehouse design)' },
      { id: 'spark-at-scale', label: 'Large-scale Spark / streaming optimization' },
      { id: 'data-platform-strategy', label: 'Data platform strategy (governance & quality)' },
      { id: 'orchestration-at-scale', label: 'Advanced workflow orchestration at scale' },
      { id: 'cloud-native-data-arch', label: 'Cloud-native data architecture' },
      { id: 'data-security', label: 'Data security & compliance' },
      { id: 'system-design', label: 'System design & architecture ownership' },
      { id: 'code-review-mentoring', label: 'Mentoring & code review' },
      { id: 'tech-roadmap', label: 'Data roadmap ownership' },
      { id: 'stakeholder-comms', label: 'Cross-team stakeholder communication' },
    ],
  },
  {
    id: 'qa-automation',
    label: 'QA Automation Engineer',
    marketDemand: { label: 'Moderate demand', points: 9 },
    coreStack: [
      { id: 'automation-framework', label: 'Automation framework (Selenium/Playwright/Cypress)' },
      { id: 'programming', label: 'Programming (Java/Python/JavaScript)' },
      { id: 'api-testing', label: 'API testing (Postman/RestAssured)' },
      { id: 'cicd-integration', label: 'CI/CD integration' },
      { id: 'performance-testing', label: 'Performance testing (JMeter)' },
      { id: 'sql', label: 'SQL' },
      { id: 'git', label: 'Git' },
      { id: 'agile-bugtracking', label: 'Agile & bug tracking (Jira)' },
      { id: 'bdd', label: 'BDD (Cucumber)' },
      { id: 'manual-testing', label: 'Manual testing fundamentals' },
    ],
  },
  {
    id: 'qa-automation-lead',
    label: 'QA Automation Lead',
    marketDemand: { label: 'Moderate demand', points: 8 },
    coreStack: [
      { id: 'test-architecture', label: 'Test architecture & strategy design' },
      { id: 'framework-design-scale', label: 'Advanced automation framework design (scalable, parallel)' },
      { id: 'perf-load-strategy', label: 'Performance & load testing strategy' },
      { id: 'quality-gates', label: 'CI/CD quality gates ownership' },
      { id: 'test-data-mgmt', label: 'Test data management & environment strategy' },
      { id: 'cross-platform-strategy', label: 'Cross-browser/cross-platform strategy' },
      { id: 'code-review-mentoring', label: 'Mentoring & code review' },
      { id: 'quality-roadmap', label: 'Quality roadmap ownership' },
      { id: 'stakeholder-comms', label: 'Cross-team stakeholder communication' },
      { id: 'standards-ownership', label: 'Process & standards ownership' },
    ],
  },
  {
    id: 'cloud-engineer',
    label: 'Cloud Engineer',
    marketDemand: { label: 'Very high demand', points: 14 },
    coreStack: [
      { id: 'cloud-core-services', label: 'Core cloud services (compute/storage/networking)' },
      { id: 'iac-terraform', label: 'Infrastructure as Code (Terraform/CloudFormation)' },
      { id: 'cloud-networking', label: 'Cloud networking (VPC/subnets/security groups)' },
      { id: 'cloud-iam', label: 'Cloud IAM & security' },
      { id: 'serverless', label: 'Serverless (Lambda/Functions)' },
      { id: 'containers', label: 'Containers (Docker/Kubernetes)' },
      { id: 'cost-management', label: 'Cost management & optimization' },
      { id: 'monitoring-logging', label: 'Monitoring & logging (CloudWatch/Azure Monitor)' },
      { id: 'migration-strategy', label: 'Cloud migration strategy' },
      { id: 'cicd-basics', label: 'CI/CD basics' },
    ],
  },
  {
    id: 'cloud-engineer-lead',
    label: 'Cloud Engineering Lead',
    marketDemand: { label: 'Very high demand', points: 13 },
    coreStack: [
      { id: 'cloud-architecture', label: 'Enterprise cloud architecture design' },
      { id: 'iac-at-scale', label: 'Infrastructure as Code at scale (Terraform modules)' },
      { id: 'multi-cloud-strategy', label: 'Multi-cloud / hybrid cloud strategy' },
      { id: 'finops', label: 'Cost optimization (FinOps)' },
      { id: 'cloud-security-architecture', label: 'Cloud security architecture' },
      { id: 'migration-leadership', label: 'Large-scale migration leadership' },
      { id: 'code-review-mentoring', label: 'Mentoring & architecture review' },
      { id: 'incident-management', label: 'Incident management / on-call ownership' },
      { id: 'stakeholder-comms', label: 'Cross-team stakeholder communication' },
      { id: 'tech-roadmap', label: 'Cloud roadmap ownership' },
    ],
  },
  {
    id: 'network-engineer',
    label: 'Network Engineer',
    marketDemand: { label: 'Moderate demand', points: 9 },
    coreStack: [
      { id: 'routing-switching', label: 'Routing & switching fundamentals' },
      { id: 'network-vendor', label: 'Vendor platforms (Cisco/Juniper)' },
      { id: 'firewalls-vpn', label: 'Firewalls & VPN configuration' },
      { id: 'dns-dhcp', label: 'DNS/DHCP administration' },
      { id: 'load-balancing', label: 'Load balancing' },
      { id: 'sdwan', label: 'SD-WAN' },
      { id: 'network-monitoring', label: 'Network monitoring (Wireshark/SolarWinds)' },
      { id: 'network-automation', label: 'Network automation (Python/Ansible)' },
      { id: 'cloud-networking', label: 'Cloud networking (VPC/VNet/Direct Connect)' },
      { id: 'network-security-basics', label: 'Network security fundamentals' },
    ],
  },
  {
    id: 'network-engineer-lead',
    label: 'Network Engineering Lead',
    marketDemand: { label: 'Moderate demand', points: 8 },
    coreStack: [
      { id: 'network-architecture', label: 'Enterprise network architecture design' },
      { id: 'sdwan-at-scale', label: 'SD-WAN / WAN strategy at scale' },
      { id: 'advanced-network-security', label: 'Advanced network security (Zero Trust, segmentation)' },
      { id: 'automation-at-scale', label: 'Network automation at scale (Ansible/Python)' },
      { id: 'cloud-network-strategy', label: 'Multi-cloud networking strategy' },
      { id: 'capacity-planning', label: 'Capacity planning & performance engineering' },
      { id: 'incident-management', label: 'Incident management / on-call ownership' },
      { id: 'code-review-mentoring', label: 'Mentoring & design review' },
      { id: 'vendor-stakeholder-mgmt', label: 'Vendor & stakeholder management' },
      { id: 'tech-roadmap', label: 'Network roadmap ownership' },
    ],
  },
  {
    id: 'cybersecurity-engineer',
    label: 'Cybersecurity Engineer',
    marketDemand: { label: 'Very high demand', points: 14 },
    coreStack: [
      { id: 'security-fundamentals', label: 'Security fundamentals (CIA triad, threat modeling)' },
      { id: 'siem', label: 'SIEM tools (Splunk/QRadar/Sentinel)' },
      { id: 'vulnerability-mgmt', label: 'Vulnerability management & scanning' },
      { id: 'pentesting-basics', label: 'Penetration testing basics' },
      { id: 'iam', label: 'Identity & access management (IAM)' },
      { id: 'cloud-security', label: 'Cloud security (AWS/Azure/GCP security services)' },
      { id: 'incident-response', label: 'Incident response & forensics' },
      { id: 'network-security', label: 'Network security (firewalls/IDS/IPS)' },
      { id: 'compliance-frameworks', label: 'Compliance frameworks (ISO 27001/SOC 2/GDPR)' },
      { id: 'security-automation', label: 'Security automation & scripting (Python)' },
    ],
  },
  {
    id: 'cybersecurity-engineer-lead',
    label: 'Cybersecurity Lead',
    marketDemand: { label: 'Very high demand', points: 13 },
    coreStack: [
      { id: 'security-architecture', label: 'Security architecture & threat modeling at scale' },
      { id: 'advanced-pentesting', label: 'Advanced penetration testing / red teaming' },
      { id: 'soc-strategy', label: 'SOC strategy & SIEM tuning at scale' },
      { id: 'cloud-security-strategy', label: 'Cloud security strategy (multi-account/multi-cloud)' },
      { id: 'iam-governance', label: 'IAM governance at scale' },
      { id: 'incident-response-leadership', label: 'Incident response leadership & tabletop exercises' },
      { id: 'compliance-ownership', label: 'Compliance & audit ownership' },
      { id: 'code-review-mentoring', label: 'Mentoring & security review' },
      { id: 'stakeholder-comms', label: 'Executive & stakeholder communication' },
      { id: 'security-roadmap', label: 'Security roadmap ownership' },
    ],
  },
];

export function getRoleById(roleId) {
  return IT_ROLES.find((role) => role.id === roleId);
}
